### ISSUE TITLE
Adding negative Numbers can get the wrong answer

### ISSUE THREAD

**Issue by podfeet** [NosillaCast/time-adder#11]
**Problem**: 
The calculation of the total number of seconds is correct, but when it's split back out into HH:MM:SS it can be wrong.

**Example**: 
(3h 20m) + (-7h -26m) 
should be -4h -6min
in time-adder is -5h 54min

**Root cause**: 
math.floor() rounds down the opposite of normal roundDown in Excel.  
The totSec/3600 is -4:10
In Excel that rounds down to -4 (expected)
math.floor() rounds it down to -5

Need to use some absolute value stuff to fix?

**Comment by westbaystars** [comment]
Maybe write your own `round(num)` function that does `Math.sign(num) * Math.round(Math.abs(num))`.

**Comment by westbaystars** [comment]
An interesting one I found Googling around is:

```
function round(num) {
  return (num >= 0 || -1) * Math.round(Math.abs(num));
}
```

When `num` is 0 or positive, `num >= 0` evaluates to `1`. 

I suspect that `Math.sign(num)` does the same thing as `(num >=0 || -1)`. So does doing the evaluation save any time over the `Math.sign` function call?

**Comment by podfeet** [comment]
Thanks, @westbaystars  - I'll take a look at all of these. Doesn't seem to be too hard to figure out now that I figured out the root cause of the error. I appreciate you giving me a head start.

**Comment by westbaystars** [comment]
It appears to be a common problem in all languages. One needs a `round_toward_zero` function to make what happens more clear.

Using Elixir's Time module on the original problem, I get:

```
iex(1)> {seconds, _miliseconds} = Time.to_seconds_after_midnight(~T[07:26:00])
{26760, 0}
iex(2)> Time.add(~T[03:20:00], -seconds)
~T[19:54:00]
```

That extracts the number of seconds past midnight for 7:26, then subtracts that number of seconds from  3:20 resulting in the time 19:54 of the previous day. But since we aren't including the date, that isn't clear from the output.

19:54 is correctly 4 hours and 6 minutes before midnight, but that's not how you want it displayed. Hmmm.

This probably isn't useful. But it's fun to approach a problem in a different language.

**Comment by podfeet** [comment]
Fixed by finding the sign of totSec, and the absolute value of totSec. Then run the math to calculate roundHours/roundMin/leftoverSec based on the absolute value and applied the sign of totSec to each value.
